### ISSUE TITLE
Use find instead of imperative forEach-loop

### ISSUE THREAD

**Issue by theikkila** [rbval/websocket-commander#1]
Use Array.prototype.find (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find)

as functional alternative for your current implementation with forEach-loop.
https://github.com/rbval/websocket-commander/blob/master/server.js#L20

**Comment by theikkila** [comment]
Find supports early return

**Comment by theikkila** [comment]
Another angle for the problem:

Is it neccessary to do O(n) search from the data (even though it's just mock data) instead of using
object and so fetching the result in O(1) time.

ie.

```
const groups = {
  1: {online: 5},
  2: {online: 3}
}
```

```
const group = 2;
const has_group = (groups, group) => group in groups;

if (!has_group(groups, group)) {
    return res.status(404).send()
}
res.send(groups[group])
```

**Comment by rbval** [comment]
Implement changes in https://github.com/rbval/websocket-commander/commit/725ae6e7f7f876d187f195cd37bb88b68c9dad2d
